using CatalogApi.Data.Repositories;
using CatalogApi.Models;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using ValidationException = OnlineStoreMVP.ServiceDefaults.Common.Exceptions.ValidationException;
using OnlineStoreMVP.ServiceDefaults.Controllers;
using OnlineStoreMVP.ServiceDefaults.Common.Exceptions;

namespace CatalogApi.Controllers;

[Route("api/[controller]")]
public class ProductsController(
    ILogger<ProductsController> logger, 
    IProductRepository productRepository,
    IValidator<ProductModel> validator) : BaseController
{
    private readonly ILogger<ProductsController> _logger = logger;
    private readonly IValidator<ProductModel> _validator = validator;
    private readonly IProductRepository _productRepository = productRepository;

    /// <summary>
    /// Creates a new product and adds it to the collection.
    /// </summary>
    /// <remarks>The product's unique identifier is generated by the server. The response includes the
    /// full product details as stored.</remarks>
    /// <param name="product">The product information to create. The product details are provided in the request body. Cannot be null.</param>
    /// <returns>A CreatedAtActionResult containing the newly created product and a location header with the URI of the
    /// created product.</returns>
    [HttpPost]
    public async Task<IActionResult> CreateProduct([FromBody] ProductModel product)
    {
        try
        {
            // Validate input
            var validationResult = _validator.Validate(product);
            if (!validationResult.IsValid)
            {
                var errors = validationResult.Errors
                    .GroupBy(e => e.PropertyName)
                    .ToDictionary(
                        g => g.Key,
                        g => g.Select(e => e.ErrorMessage).ToArray()
                    );
                throw new ValidationException(errors);
            }

            // Business logic
            var createdProduct = await _productRepository.AddAsync(product);

            return CreatedAtAction(nameof(CreateProduct), new { id = createdProduct.Id }, createdProduct);
        }
        catch (Exception ex)
        {
            return HandleException(ex, _logger, nameof(CreateProduct));
        }
    }

    /// <summary>
    /// Updates the details of an existing product with the specified identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the product to update.</param>
    /// <param name="updatedProduct">An object containing the updated product information. All required fields must be provided.</param>
    /// <returns>An HTTP 204 No Content response if the update is successful; otherwise, an HTTP 404 Not Found response if
    /// the product does not exist.</returns>
    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateProduct(Guid id, [FromBody] ProductModel updatedProduct)
    {
        try
        {
            // Validate input
            var validationResult = _validator.Validate(updatedProduct);
            if (!validationResult.IsValid)
            {
                var errors = validationResult.Errors
                    .GroupBy(e => e.PropertyName)
                    .ToDictionary(
                        g => g.Key,
                        g => g.Select(e => e.ErrorMessage).ToArray()
                    );
                throw new ValidationException(errors);
            }

            var product = await _productRepository.UpdateAsync(id, updatedProduct) ?? throw new NotFoundException(nameof(ProductModel), id);

            return NoContent();
        }
        catch (Exception ex)
        {
            return HandleException(ex, _logger, nameof(UpdateProduct));
        }
    }

    /// <summary>
    /// Retrieves the available products.
    /// </summary>
    /// <returns>An <see cref="IActionResult"/> containing the list of products. The response has a status code of 200 (OK)
    /// with the products in the response body.</returns>
    [HttpGet]
    public async Task<IActionResult> GetProducts()
    {
        try
        {
            var products = await _productRepository.GetAllAsync();
            return Ok(products);
        }
        catch (Exception ex)
        {
            return HandleException(ex, _logger, nameof(GetProducts));
        }
    }

    /// <summary>
    /// Retrieves the product with the specified unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the product to retrieve.</param>
    /// <returns>An <see cref="OkObjectResult"/> containing the product if found; otherwise, a <see cref="NotFoundResult"/>
    /// if no product with the specified identifier exists.</returns>
    [HttpGet("{id}")]
    public async Task<IActionResult> GetProduct(Guid id)
    {
        try
        {
            var product = await _productRepository.GetByIdAsync(id) ?? throw new NotFoundException(nameof(ProductModel), id);
            
            return Ok(product);
        }
        catch (Exception ex)
        {
            return HandleException(ex, _logger, nameof(GetProduct));
        }
    }

    /// <summary>
    /// Deletes the product with the specified unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the product to delete.</param>
    /// <returns>An <see cref="IActionResult"/> that represents the result of the delete operation. Returns <see
    /// cref="NotFoundResult"/> if the product does not exist; otherwise, returns <see cref="NoContentResult"/> on
    /// successful deletion.</returns>
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteProduct(Guid id)
    {
        try
        {
            if (await _productRepository.DeleteAsync(id) is false)
            {
                throw new NotFoundException(nameof(ProductModel), id);
            }

            return NoContent();
        }
        catch (Exception ex)
        {
            return HandleException(ex, _logger, nameof(DeleteProduct));
        }
    }
}
