using CatalogApi.Models;
using Microsoft.AspNetCore.Mvc;

namespace CatalogApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductsController : ControllerBase
    {
        private static List<ProductModel> _products =
        [
            new ProductModel { Id = Guid.NewGuid(), Description = "Product A", Name = "Product A", Price = 10.0m, Stock = 10 },
            new ProductModel { Id = Guid.NewGuid(), Description = "Product B", Name = "Product B", Price = 20.0m, Stock = 20 },
            new ProductModel { Id = Guid.NewGuid(), Description = "Product C", Name = "Product C", Price = 30.0m, Stock = 30 }
        ];

        /// <summary>
        /// Retrieves the available products.
        /// </summary>
        /// <returns>An <see cref="IActionResult"/> containing the list of products. The response has a status code of 200 (OK)
        /// with the products in the response body.</returns>
        [HttpGet]
        public IActionResult GetProducts() => Ok(_products);

        /// <summary>
        /// Retrieves the product with the specified unique identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the product to retrieve.</param>
        /// <returns>An <see cref="OkObjectResult"/> containing the product if found; otherwise, a <see cref="NotFoundResult"/>
        /// if no product with the specified identifier exists.</returns>
        [HttpGet("{id}")]
        public IActionResult GetProduct(Guid id)
        {
            var product = _products.FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return Ok(product);
        }

        /// <summary>
        /// Creates a new product and adds it to the collection.
        /// </summary>
        /// <remarks>The product's unique identifier is generated by the server. The response includes the
        /// full product details as stored.</remarks>
        /// <param name="product">The product information to create. The product details are provided in the request body. Cannot be null.</param>
        /// <returns>A CreatedAtActionResult containing the newly created product and a location header with the URI of the
        /// created product.</returns>
        [HttpPost]
        public IActionResult CreateProduct([FromBody] ProductModel product)
        {
            product.Id = Guid.NewGuid();

            _products.Add(product);

            // save the product to a database
            return CreatedAtAction(
                nameof(GetProduct),
                new { id = product.Id },
                product);
        }

        /// <summary>
        /// Updates the details of an existing product with the specified identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the product to update.</param>
        /// <param name="updatedProduct">An object containing the updated product information. All required fields must be provided.</param>
        /// <returns>An HTTP 204 No Content response if the update is successful; otherwise, an HTTP 404 Not Found response if
        /// the product does not exist.</returns>
        [HttpPut("{id}")]
        public IActionResult UpdateProduct(Guid id, [FromBody] ProductModel updatedProduct)
        {
            var product = _products.FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            // update the product in the database
            product.Name = updatedProduct.Name;
            product.Description = updatedProduct.Description;
            product.Price = updatedProduct.Price;
            product.Stock = updatedProduct.Stock;

            _products[_products.IndexOf(product)] = product;

            return NoContent();
        }

        /// <summary>
        /// Deletes the product with the specified unique identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the product to delete.</param>
        /// <returns>An <see cref="IActionResult"/> that represents the result of the delete operation. Returns <see
        /// cref="NotFoundResult"/> if the product does not exist; otherwise, returns <see cref="NoContentResult"/> on
        /// successful deletion.</returns>
        [HttpDelete("{id}")]
        public IActionResult DeleteProduct(Guid id)
        {
            var product = _products.FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            // delete the product from the database
            _products.Remove(product);
            return NoContent();
        }
    }
}
